name: CD

on:
  release:
    types:
      - "published"

jobs:
  test:
    name: Publish to NPM
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup NPM GH_TOKEN
        run: |
          npm config set _authToken=${{ secrets.NPM_TOKEN }}

      - name: Install Deps
        run: npm ci

      - name: Publish to NPM
        run: npm publish

